### ISSUE TITLE
Unable to add SPM package due to 403 error

### ISSUE THREAD

**Issue by EliSawic** [pingidentity/pingone-mobile-sdk-ios#34]
Hello, starting from today it turned out that I'm unable to fetch the SDK in my project. I end up with 403 error while fetching the framework.
Are you aware of such problem?

This is a message from Xcode.
Showing All Messages
failed downloading 'https://assets.pingone.com/pingonemobile/ios-sdk/release/PingOneSDK.xcframework.1.8.1.zip' which is required by binary target 'PingOneSDK': badResponseStatusCode(403)

**Comment by amitnadirping** [comment]
Hello,
Thanks for raising this comment.
Indeed there was a temporary issue, now the PingOne framework is available again. 
@EliSawic please try again

**Comment by EliSawic** [comment]
Works now, thanks :)
