### ISSUE TITLE
Re-registering Devices in PingOne without Application Termination

### ISSUE THREAD

**Issue by HenryDouglasZLabs** [pingidentity/pingone-mobile-sdk-ios#40]
Dear PingOne SDK Team,

I hope this message finds you well. I am writing to report an issue that I have encountered while working with the PingOne SDK. My scenario involves the registration of multiple devices under the same user within the same application session.

Here is the sequence of events:

Device 1 Registration: Successfully registered Device 1 with PingOne SDK.

Device 2 Registration: While Device 1 is registered and operational, I attempted to register Device 2 with the same user using PingOne SDK. The registration for Device 2 was successful.

Device 1 Re-registration Attempt: At this point, as a user, I attempted to re-register Device 1 with PingOne SDK without terminating the application. However, PingOne SDK responded with an error, stating "Domain=PingOneErrorDomain Code=10013 "Pairing is currently in progress - you cannot make another API call until it is completed." UserInfo={type=sdk, NSLocalizedDescription=Pairing is currently in progress - you cannot make another API call until it is completed., internalErrorCode=20080}"

Successful Registration After Application Termination: When I terminated the application and re-launched it, I retried registering Device 1 with PingOne SDK, and this time it was successful.

Issue Details:

It seems that there is an issue when attempting to re-register a device with PingOne SDK without terminating the application. The error message, "Domain=PingOneErrorDomain Code=10013 "Pairing is currently in progress - you cannot make another API call until it is completed." UserInfo={type=sdk, NSLocalizedDescription=Pairing is currently in progress - you cannot make another API call until it is completed., internalErrorCode=20080}," is encountered, preventing successful registration.

Expected Behavior:

The SDK should allow re-registration of a device without requiring the termination of the application. Users should be able to seamlessly register and re-register devices during a single application session.

Please let me know if you need any further information, logs, or assistance in resolving this matter. I appreciate your prompt attention to this issue and look forward to a resolution.

Thank you.

Best regards,
Henry Douglas.

**Comment by asafd1** [comment]
Hi Henry, 
I'm not sure what are the steps you are performing: how do you try to re-register an already registered device for the same user? are you unpairing first?
Anyway, I'd suggest creating a support ticket for this so we can investigate.

**Comment by adavid-pingidentity** [comment]
Hi Henry,
I'm not sure what are the steps you are performing: how do you try to re-register an already registered device for the same user? are you unpairing first?
Anyway, I'd suggest creating a support ticket for this so we can investigate.

**Comment by amitnadirping** [comment]
Hi Henry,
Thanks for adding more details to your comment above.
The error code 10013 indicates that the client is attempting to start a new pairing process before the last one has completed, as documented [here](https://pingidentity.github.io/pingone-mobile-sdk-ios/documentation/pingonesdk/errorcode/pairingalreadyrunning#declaration). Please ensure that the app code does not allow firing additional pair / oidc requests before the completion of the former one. If there are still any doubts, please be sure to create a ticket for this in [here]( https://support.pingidentity.com/s/topic/0TO1W000000atTxWAI/pingone-mfa).

**Comment by amitnadirping** [comment]
The issue above, regarding multiple user pairing with OIDC, will be solved in the upcoming version 1.10.1, which will be published soon.

**Comment by amitnadirping** [comment]
The issue above, regarding multiple user pairing with OIDC, will be solved in the upcoming version 1.10.1, which will be published soon.
