### ISSUE TITLE
App installation failed: Unable to Install Xcode 15.3

### ISSUE THREAD

**Issue by learnwithgabbar** [pingidentity/pingone-mobile-sdk-ios#41]
After updating to Xcode 15.3, I encountered issues installing the app on the simulator and the device.

`Please try again later. Failed to load Info.plist from bundle at path /Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework; Extra info about "/Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework/Info.plist": Couldn't stat /Users/xyz/Library/Developer/CoreSimulator/Devices/71205805-06B2-49C1-BCDD-9E7EC03D2141/data/Library/Caches/com.apple.mobile.installd.staging/temp.pTEd70/extracted/Payload/PFJ Internal.app/Frameworks/PingOneSignals.framework/Info.plist: No such file or directory`

**Comment by EvgeniyMish** [comment]
@learnwithgabbar seems like this issue belongs to another project and I see you've opened another one in the correct repository: https://github.com/pingidentity/pingone-signals-sdk-ios/issues/1
